#nameOverride: "hour-reporting"
#fullnameOverride: "hour-reporting"
#ingress:
#  enabled: true
#  hosts:
#    - "hour-reporting-{{- .Release.Namespace -}}-test.k8s.ispworks.nl"

options:
  java: ""
  application: ""
  logger: json
configuration:
  database:
    host: "mysql-martijn.martijnk.svc.cluster.local"
    port: 3306
    poolSize: 2
    schema: "hour-reporting"
    timeZone: "UTC"
    username: "test"
    password: "test"
  microsoft:
    clientId: client
    clientSecret: secret
    clientScopes: "openid,profile,https://graph.microsoft.com/Calendars.Read,https://graph.microsoft.com/MailboxSettings.Read"
  keys:
    privateKey: "asdfasdf"
    publicKey: "asdfasdf"

secret:
  database:
    existing: true
    name: "jira-statistics-secret"
    usernameKey: "database.username"
    passwordKey: "database.password"
  microsoft:
    existing: true
    name: "microsoft-credentials-secret"
    clientId: "microsoft.clientId"
    clientSecret: "microsoft.clientSecret"
  keys:
    existing: true
    name: "encryption-keys"
    privateKeyKey: "private_key.pem"
    publicKeyKey: "public_key.pem"

livenessProbe:
  httpGet:
    path: /health
    port: 1234
  initialDelaySeconds: 5
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /health
    port: 1234
  initialDelaySeconds: 30
  timeoutSeconds: 5

prometheus:
  enabled: false
  port: 8080
  path: '/metrics'

image:
  repository: "ghcr.io"
  image: "ghcr.io/mtijn/hour-reporting/hour-reporting"
  tag: "latest"

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/whitelist-source-range: "89.184.180.107/32, 89.184.168.160/32"
    ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
    kubernetes.io/ingress.class: "traefik"
  path: /
  hosts:
    - hour-reporting.k8s.ispworks.nl
  backend_port: 8080

volumeMounts:
  - name: encryption-keys
    mountPath: "/encryption-keys"

volumes:
  - name: encryption-keys
    secret:
      secretName: "encryption-keys"
      items:
        - key: "private_key.pem"
          path: "private_key.pem"
        - key: "public_key.pem"
          path: "public_key.pem"
