#nameOverride: "hour-reporting"
#fullnameOverride: "hour-reporting"
#ingress:
#  enabled: true
#  hosts:
#    - "hour-reporting-{{- .Release.Namespace -}}-test.k8s.ispworks.nl"

options:
  java: ""
  application: ""
  logger: json
configuration:
  database:
    host: "database.jdbc.url"
    poolSize: 2
    username: "test"
    password: "test"
  microsoft:
    clientId: client
    clientSecret: secret
    clientScopes: "openid,profile,https://graph.microsoft.com/Calendars.Read,https://graph.microsoft.com/MailboxSettings.Read"
  keys:
    privateKey: "asdfasdf"
    publicKey: "asdfasdf"

secret:
  database:
    existing: false
    name: "hour-reporting-secret"
    usernameKey: "database.username"
    passwordKey: "database.password"
  microsoft:
    existing: false
    name: "microsoft-client-credentials"
    clientId: "microsoft.clientId"
    clientSecret: "microsoft.clientSecret"
  keys:
    existing: false
    name: "encryption-keys"
    privateKeyKey: "private_key.pem"
    publicKeyKey: "public_key.pem"

livenessProbe:
  httpGet:
    path: /health
    port: 1234
  initialDelaySeconds: 5
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /health
    port: 1234
  initialDelaySeconds: 30
  timeoutSeconds: 5

prometheus:
  enabled: false
  port: 8080
  path: '/metrics'

image:
  repository: "ghcr.io"
  image: "mtijn/hour-reporting"
  tag: "0.0.1"

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/whitelist-source-range: "123.123.123.10"
    ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
    kubernetes.io/ingress.class: "traefik"
  path: /
  hosts:
    - some-host
  backend_port: 8080

volumeMounts:
  - name: encryption-keys
    mountPath: "/encryption-keys"

volumes:
  - name: encryption-keys
    secret:
      secretName: "encryption-keys"
      items:
        - key: "private_key.pem"
          path: "private_key.pem"
        - key: "public_key.pem"
          path: "public_key.pem"
