{{- if not .Values.secret.database.existing }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "Database secret name" .Values.secret.database.name }}
  labels:
    app.kubernetes.io/name: {{ include "hour-reporting.name" . }}
    helm.sh/chart: {{ include "hour-reporting.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ required "Database secret username key" .Values.secret.database.usernameKey }}: {{ required "Database username" .Values.configuration.database.username | b64enc | quote }}
  {{ required "Database secret password key" .Values.secret.database.passwordKey }}: {{ required "Database password" .Values.configuration.database.password | b64enc | quote }}
{{- end -}}
{{- if not .Values.secret.jira.existing }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "Hour reporting secret name" .Values.secret.microsoft.name }}
  labels:
    app.kubernetes.io/name: {{ include "hour-reporting.name" . }}
    helm.sh/chart: {{ include "hour-reporting.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ required "Client ID" .Values.secret.microsoft.clientId }}: {{ required "Client ID" .Values.configuration.microsoft.clientId | b64enc | quote }}
  {{ required "Client Secret" .Values.secret.microsoft.clientSecret }}: {{ required "Client Secret" .Values.configuration.microsoft.clientSecret | b64enc | quote }}
{{- end -}}
