name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk
      - name: Linting
        run: mvn antrun:run@ktlint
      - name: Maven Test
        run: mvn -B clean test
