on:
  release:
    types: [published]

name: Build
jobs:
  Build:
    name: Build Jar file
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Upload jar for job 1
        uses: actions/upload-artifact@v1
        with:
          name: jarpack
          path: ./target


  package:
    name: Publish - Packages
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/hour-reporting
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
